### PR TITLE
prefer fn#bind(this) to var self = this

### PR DESCRIPTION
**Pull request by tejasmanohar**
i'd say that since everyone using nightmare is es5+, Function#bind should be preferred to the `var self = this` strategy since rebinding `this` is the end goal and we don't have to declare another variable.

thoughts?

### CODE REVIEW

**Comment by matthewmueller** [comment]
whenever i see this change, i always wonder about the benchmarks, since we're wrapping every function in another function, as opposed to just points to the `this` ref. do you have any benchmarks of this being a negligible change? doesn't have to be nightmare specific but just in general?

**Comment by rosshinkley** [comment]
@matthewmueller FWIW, there's a decent looking [jsperf](https://jsperf.com/bind-vs-closure-setup/49).  According to that, it looks like the `bind` method is significantly slower.  Is that close to what you had in mind?

**Comment by matthewmueller** [comment]
@rosshinkley yep this is exactly what i was looking for:

img

even though it's a micro optimization, i don't think using `self` is much worse syntactically.

**Comment by tejasmanohar** [comment]
aha, nope- i did not have a stat for this but am glad to see this one- didn't know...

**Pull request closed without merging**
