### PR TITLE
Use node-integration for electron, fix #247 & amd scripts loading

### LINKED ISSUE #247: $ is not defined, module ipc is not availiable
I am getting a lot of errors like $ is not defined, module ipc is not availiable, could not load jquery when i tried to login to linkedin using nightmare. Can you please tell how i can resolve this?

### PR DESCRIPTION
**Pull request by fritx**
~~Sorry for the extra field in package.json & a missing semicolon, but I think they could be fixed with the next bump clean~~ (cleaned) ;) fix #247 #242

### CODE REVIEW

**Comment by matthewmueller** [comment]
Thanks for the PR! Can you explain in a little more detail what this does to fix the problem? Some questions I have:

- Was the missing semicolon causing us to not get the errors?
- What's the purpose of preloading and disabling node-integration?

**Comment by fritx** [comment]
@matthewmueller ok.

- No, forget the missing semicolon. I meant it was I that had [missed a semicolon](https://github.com/segmentio/nightmare/pull/250/files#diff-9dcc65cc4a6c14eb4f81fbe4005301d0R41) in my PR commit, but just leave it ;)
- Yes, with `node-integration` turned off:
 - electron won't expose node stuff like `module/exports` to the web
 - so we could correctly load any webpage with many scripts like jquery that depends on a `module/exports` detection
 - and with a `preload` script we can still inject anything with node access just like what we do, but only at the very beginning.

**Comment by fritx** [comment]
See also: https://github.com/sindresorhus/caprine/blob/master/index.js#L39

**Comment by fritx** [comment]
Let me clean my commit to be better.

**Comment by fritx** [comment]
@matthewmueller once this problem solved, in #249 i'd suggest we replace `google.com` to `github.com`, and it'd get to work. ;)

**Comment by matthewmueller** [comment]
thanks buddy, appreciate the research!

i'm fine with changing the tests to point to github to avoid the great firewall. open a pr and i'll accept :+1:

**Comment by fritx** [comment]
cool, thanks much! @matthewmueller

**Pull request merged**
