### PR TITLE
Synchronize screenshots using frame subscription API

### PR DESCRIPTION
**Pull request by Mr0grog**
This is meant to address #468.

The basic gist of the change is to add a `FrameManager` object that emits events whenever the browsers renders a new frame and use that to figure out when to call `capturePage()`.

Some notes:

- At current, this can trigger pretty massive memory consumption. Due to a bug in Electron (https://github.com/atom/electron/issues/4441), trying to unsubscribe from frames can cause a crash (and there's no way to know whether that will happen ahead of time and smartly wait until it's safe). That means that, once we start subscribing, we don't stop until the window is closed (i.e. until nightmare's `end()` method is called).

  For reference, a really simple nightmare session takes 20-30 MB of RAM on my machine, but once a screenshot is taken, that can boost to as high as 360 MB. (You can actually watch V8 manage memory here—the electron process will slowly grow to a few hundred megabytes and then get chopped back down to less than 50, then start growing again…)

  Anyway, there's already a patch on the way for this in Electron (https://github.com/atom/electron/pull/4451), but I don't know when it will land and ship. Once it does, the code here can be very easily adjusted to smartly unsubscribe if it's safe based on the version of Electron we're running in: https://github.com/Mr0grog/nightmare/blob/a179e2ed6e7b1d72d8cd518a9b464c0bf0a68220/lib/frame-manager.js#L11

- FrameManager is an event emitter, so it could pretty easily support some interesting other behaviors in the future, like rendering video of the page in action. It knows how to manage frame subscriptions in Electron when listeners are attached/detached.

- It's likely this would be better off in that future case as a readable stream, but managing push/pull/buffering vs. whenever Chromium decides to render a frame seemed potentially non-trivial (or at least require lots of testing and probably some nuance with finding an appropriate high-water mark), so I didn't bother with that for now.

Anyway, hope this helps and looks good to you all. It's covered by tests, too. Let me know if there's anything that should be changed.

### CODE REVIEW

**Comment by Mr0grog** [comment]
There is a shipping version of Electron with the fix for the crash now! I've added semver support for checking the electron version to see if it's safe to unsubscribe. Alternatively, we could just bump the minimum required version of electron-prebuilt in `package.json`.

**Comment by rosshinkley** [comment]
I'd vote for simply upping the Electron version, barring other changes made internally to Electron.  Is there a reason not to?

At any rate: +1 for this PR. :)

**Comment by Mr0grog** [comment]
@rosshinkley No reason not to bump the version as far as I'm aware. Figured I'd go for safety first, though, since I didn't know if there was any policy around Electron versions.

**Comment by rosshinkley** [comment]
@Mr0grog I can't find it with a cursory search, but I'm almost positive the version has been upped to accommodate changes like this before.  There are plenty of issues surrounding version changes where Electron changed some sort of internal convention (preference names like `web-preferences` to `webPreferences`, for example).  I think I'd still rather manage the version bump fallout over managing version compatibility, though.

**Comment by Mr0grog** [comment]
@rosshinkley Makes sense, thanks for the feedback. Bumped the version and eliminated all the `CAN_UNSUBSCRIBE` stuff in f4499d0ff5145a6082c7630dfba51c100a760d1f. :thumbsup:

**Comment by Mr0grog** [comment]
Howdy! It’s been a few weeks with no official feedback, so I’m just checking in. Any idea when you might get a chance to take a look at this?

**Comment by mikeys** [comment]
@Mr0grog I'm using the `FrameManager` code and from time to time I still experience problems with incomplete/blank captures.
Perhaps it has to do with the fact that we rely on the first `buffer` event, but I've noticed that sometimes I get 2 and more events (depends on the complexity of the item being rendered?)
I've noticed that adding `beginFrameSubscription(debounce(receiveFrame, frameDebounce)` produces more consistent results.

**Comment by Mr0grog** [comment]
> Perhaps it has to do with the fact that we rely on the first buffer event, but I've noticed that sometimes I get 2 and more events (depends on the complexity of the item being rendered?)

Well, anything that happens in the window that causes rendering (even moving the mouse around) can cause frames to be rendered, so I don’t think it would be at all surprising to see more than one frame event. I suppose it’s possible that there could also be frames already queued up at the time of subscription that we receive when first subscribing, so you might also be seeing that.

Given that, I can definitely see how debouncing could be improve accuracy (though at a significant time cost). You should submit a PR! (FYI I’m not a maintainer/committer here; I can’t approve or merge anything for you.)

**Pull request merged**
