### PR TITLE
Added hook to append chromium arguments

### PR DESCRIPTION
**Pull request by yotamlaufer**
https://github.com/electron/electron/blob/master/docs/api/app.md#appcommandlineappendargumentvalue

List of arguments:
http://peter.sh/experiments/chromium-command-line-switches/

### CODE REVIEW

**Comment by rosshinkley** [comment]
I'm okay with this change.  Would you mind adding to the readme to cover the option and where to find Chromium switches?

**Comment by yotamlaufer** [comment]
done

**Comment by rosshinkley** [comment]
@yotamlaufer Awesome, thank you.

**Comment by yotamlaufer** [comment]
With please. I love nightmare!

**Comment by Mr0grog** [comment]
Curious question: why name this `chromiumArguments` when the corresponding switches version is just `switches` (no “chromium” prefix)?

**Comment by Mr0grog** [comment]
Also, tests?

**Comment by casesandberg** [comment]
Can you update this to have no merge conflicts and then I can merge it in?

**Comment by matthewmueller** [comment]
Going to close this since this PR is stale. Thanks for your efforts!

**Pull request closed without merging**
