### PR TITLE
Support Chrome command line switches

### PR DESCRIPTION
**Pull request by juanpaulo**
Support [Chrome command line switches](https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md) (e.g. proxy-server, ignore-certificate-errors).

### CODE REVIEW

**Comment by matthewmueller** [comment]
wow awesome, thanks!

**Comment by catblade** [comment]
Hey, can we change proxies on the fly or just on the opening of nightmare?

**Comment by geostant** [comment]
using proxy-server switch use http proxy,
how can I set it to sock proxy ?

Thanks

**Comment by juanpaulo** [comment]
This PR adds support for electron's [Chrome command line switches](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md). I haven't tried changing proxies on the fly nor use socks proxy so I can't really say that it works or not. Feel free to try them yourself and please don't forget to share how you did it if it works! ;)

**Comment by wiliame** [comment]
@catblade have you found how to change proxies on the fly? I'm going to open a issue for  that.

**Comment by catblade** [comment]
@wiliame There is a way.  I'll get you a code snippet this evening.

**Comment by wiliame** [comment]
@catblade thanks, I figured it out.

https://github.com/segmentio/nightmare/issues/908

I'm now trying to figure this other one:

https://github.com/electron/electron/issues/8089

**Comment by Momohime** [comment]
@geostant This might come a little bit late, but just prepend 'socks5://' to your proxy-server switch to instruct the driver to use socks5 instead of regular http proxy.

For example: 

`var nightmare = Nightmare( { switches: { 'proxy-server': 'socks5://' + '127.0.0.1:1080', 'ignore-certificate-errors': true } } );`

**Pull request merged**
