### PR TITLE
Update proxy info

### PR DESCRIPTION
**Pull request by agrberg**
Add useful information found in issue #665 for devs looking for proxy info.

### CODE REVIEW

**Comment by agrberg** [comment]
I'm not married to the changes in the first two commits so if you don't like them, I'm happy to drop them.

**Comment by rosshinkley** [comment]
Keeping the documentation consistent: could you move the `.evaluate()` and `.then()` methods to be inline?

**Comment by rosshinkley** [comment]
By the by, the first two commits: +1.  Those are logical changes.

**Comment by agrberg** [comment]
Sure thing. I intended that to reduce the duplication but it's minimal and might make things easier on the reader. One sec and I'll have an update.

**Comment by agrberg** [comment]
@rosshinkley updated, thanks for the review

**Comment by rosshinkley** [comment]
Awesome.  Thanks! :)

**Pull request merged**
