### PR TITLE
Cookies & proxy support

### PR DESCRIPTION
**Pull request by yura415**

### CODE REVIEW

**Comment by matthewmueller** [comment]
Wow awesome! Definitely think both of these features should be in Nightmare.

Two things:

- Would be good if you could open 2 separate PRs since these features are unrelated and it allows us to discuss each feature separately

-  Not too keen on the API for cookies. I think it should look more like the express/koa cookie getters and setters: https://github.com/pillarjs/cookies

The `tl;dr`

```js
cookie(name, value) // set a cookie 
cookie({ a: value, b: value }) // set multiple cookies
cookie(name) // get a cookie
cookie(name, null) // delete a cookie
cookie(null) // delete all cookies
```

**Comment by yura415** [comment]
Ok, definitely should rework this since node is already supporting yields and promises.
Should i remove this PR and start two separate forks?

**Comment by yura415** [comment]
Also i thought that you should set proxy as
`.proxy(host, port, protocol)`

**Comment by matthewmueller** [comment]
Yah if its not too much work, I'd branch off master and cherry pick from
this branch then push new PRs.

I really like this PR except for the API. Not sure that you need to do
anything more (promises/yields) than just do some argument checking with
.cookie(...)

Re: proxy Api. I think you should support whatever mongodb
client/socketio/redis client support. I believe thats a string you parse or
multiple arguments, but it'd be good to have a consistent signature

Thanks again for the hard work!

**Comment by QuentinDejean** [comment]
Hey guys,

Any luck we'll see this PR merged anytime soon? Playing with cookies exactly what I am after for my tests :)

Cheers

**Comment by matthewmueller** [comment]
Would love to see this fixed up and merged!

**Comment by joernroeder** [comment]
:+1: me too :)

**Comment by flashhhh** [comment]
And me! :)

**Comment by QuentinDejean** [comment]
Hey guys,
This PR has been going for some time now.. Is there anything we can do to help? Looks like there is only one test not passing against the build

**Comment by matthewmueller** [comment]
I've added cookie support to master. I'd love to see a new PR for just the proxy support :+1:

**Comment by matthewmueller** [comment]
Closing for now, since this is woefully out of date. Would love to see someone open up a new PR with proxy support though!

**Pull request closed without merging**
