### PR TITLE
Fix javascript execution race condition on electron side

### PR DESCRIPTION
**Pull request by cchamplin**
Adds an identifier to javascript responder events for electron code invocations.

Should fix: https://github.com/segmentio/nightmare/issues/727

### CODE REVIEW

**Comment by ft232r** [comment]
👍

**Comment by reinpk** [comment]
happy to consider, but the tests are failing: https://circleci.com/gh/segmentio/nightmare/918

**Comment by Timer** [comment]
Ah, so this is why everything is blowing up! `nightmare` doesn't support concurrency. 👎
@cchamplin do you plan on reviving this PR or should I pickup the torch? 😄

**Comment by casesandberg** [comment]
Can you update this to make sure it's passing all of the tests and resolve merge conflicts? I'd be happy to re-review it then and get it merged in.

**Comment by matthewmueller** [comment]
Going to close this since this PR is stale. Thanks for your efforts!

**Pull request closed without merging**
