### PR TITLE
add `cookies(callback)`

### PR DESCRIPTION
**Pull request by atian25**
can read cookies and modify, but can't add new cookies cause I got problem with `this.page.addCookies`

Signed-off-by: TZ <atian25@qq.com>

### CODE REVIEW

**Comment by MatthewMueller** [comment]
+1

**Comment by aniforprez** [comment]
If this works, why hasn't this pull request been accepted yet?

**Comment by reinpk** [comment]
would love to see this in `2.x`: https://github.com/atom/electron/blob/master/docs/api/session.md#methods

**Comment by reinpk** [comment]
coming through #241 or related

**Pull request closed without merging**
