### PR TITLE
Add sendInputEvent, update to latest Electron

### PR DESCRIPTION
**Pull request by inversion**
sendInputEvent wasn't implemented in Electron 0.33 so I bumped the dependency, tests seem ok. Happy to add a test for sendInputEvent if needed.

### CODE REVIEW

**Comment by matthewmueller** [comment]
Awesome! So we're planning on making this a little more high-level, so `.click(...)`, `.rightclick(...)`, etc. will use this function internally to execute their events.

Let me know if you want to hack on this, otherwise I'm planning on working on it sometime this week or the next.

**Comment by inversion** [comment]
Hi @matthewmueller - I'm currently using it to implement drag and drop as well. (I've made an action which can drag and drop from/to page pixel positions, and you can also pass DOM selectors or functions to evaluate for it to determine those positions).

Internally it uses mouseDown/Move/Up and could also use touchStart/Move/End for mobile simulation.

I'd like to contribute that as I think it could be useful generally. Any thoughts? It would be easy to port without a public sendInputEvent action anyway.

Also just on the upgrade side you'll notice some deprecation warnings with the new Electron which I haven't looked into.

Cheers,
Andrew

**Comment by matthewmueller** [comment]
Wow that's really cool. I'm wondering if that would make more sense as a plugin once we land actions/use.  What do you think?

Thanks for the heads up on the electron warnings!

**Comment by inversion** [comment]
Agreed on the plugin, let's move discussion to #336

**Comment by maxfriedmann** [comment]
Hi @inversion, I stumbled over this issue since I also need some drag and drop functionality. Have you released anything in that direction? Maybe a drag and drop action/plugin?

**Comment by inversion** [comment]
Hi @maxfriedmann - I haven't got anything released for it yet, but the approach I took is basically sending the input events `mouseDown mouseMove (several) mouseUp`. The issues to consider are finding the start and end co-ordinates, choosing where to pick up the element and where to drop it (e.g. if you are trying to drop something that needs to be entirely in a target area, or if there are other target areas adjacent which can be mistakenly dropped into.

**Pull request closed without merging**
