### PR TITLE
Fixes segmentio/nightmare#742 - .wait(element, timeout) implementation

### PR DESCRIPTION
**Pull request by noahtkeller**
modified:   lib/actions.js

* map .wait(selector, timeout)->args[1] to this.options.waitTimeout if typeof === 'number'

### CODE REVIEW

**Comment by rosshinkley** [comment]
A couple of explicit tests for this would be nice.  One handling the timeout, one handling the element existing before the timeout should be sufficient.  Thoughts?

**Comment by noahtkeller** [comment]
Sure, I will write them up in a bit.

**Comment by noahtkeller** [comment]
@rosshinkley I have added the test for timeout when no element exists, and it passes. Above you mention "one handling the element existing before the timeout", this test existed already for the .wait(selector) call, so for the .wait(selector, timeout) call I just added a non-existent selector and 150ms to ensure it still passes, it does not pass if I just wait for the ul.

Is there another specific case you want me to test for?

**Comment by rosshinkley** [comment]
@noahtkeller I think this is probably sufficient for now.  Thanks!

**Pull request merged**
