### PR TITLE
Trying to adjust example.js and the matching markdown readme to work out of the box

### PR DESCRIPTION
**Pull request by oliviervaillancourt**
Hi,

While trying to test nightware, I had to modify the example.js a little bit.  It seems that yahoo.com may have removed the 'title' attribute on the search input.  

Also the readme tells you to node yahoo.js instead of example.js.

Maybe I misunderstood something.  But if this was really a correction to be done, here it is.

Thanks

### CODE REVIEW

**Comment by Mr0grog** [comment]
Hi @oliviervaillancourt, the selectors in the README were specifically chosen to be more robust against the regular changes Yahoo makes and they do still work: https://github.com/segmentio/nightmare/pull/613

It looks like it’s just `example.js` that is out of date (my bad; I completely failed to update it in the above PR.)

**Comment by oliviervaillancourt** [comment]
Hi Rob,

Thanks for taking the time to look into my PR.  I see the more robust way of doing selector in PR 613.  

I'm still having this issue and I'm not sure if it's because I misunderstood something or the PR hasn't been merged yet.

Anyways, I've made a video of what I'm doing and you can have a look to if you want.

[https://onedrive.live.com/redir?resid=9A82B122E214504!6250&authkey=!ALWRmtGHO62jr_M&ithint=video%2cmp4 ](https://onedrive.live.com/redir?resid=9A82B122E214504!6250&authkey=!ALWRmtGHO62jr_M&ithint=video%2cmp4)

Thanks

**Comment by Mr0grog** [comment]
@oliviervaillancourt Right, your issues are with:

- README should say to run `node node_modules/nightmare/example.js`
- The actual content of `example.js` doesn’t match the example in the README

Both of those things totally need to be fixed! :thumbsup: on your PR changing those. I was only trying to say that it probably shouldn’t change the example code (not the shell command) that is currently in the README (and, where it changes `example.js`, it should match the code in the README). Sorry if I worded it poorly!

**Comment by oliviervaillancourt** [comment]
Hey Rob,

Sounds like we are on the same page now and I completely agree with the way you stated things.

I guess at this point, although my PR is not exactly the best, you have enough to make the changes required.

If you need me to update the PR, let me know but I'll assume you have enough info to make the changes.

Thanks for taking the time to help me understand.  I'll continue to play around with nightmare

**Comment by Mr0grog** [comment]
> you have enough to make the changes required.

I’m not a committer and don’t have any more rights to make changes than you do, so you should probably keep working on this PR. (I just thought I’d give some feedback since I wrote #613 and knew a little bit about the stuff you were touching here.)

**Comment by oliviervaillancourt** [comment]
Ah,  got it.

Thanks for your input.  I'll look into that.

Thanks

**Comment by rosshinkley** [comment]
@oliviervaillancourt just to +1 what @Mr0grog was saying: _please_, by all means, keep going.  The more contributors, the more people we have involved, the better. :)

**Comment by oliviervaillancourt** [comment]
Created a new PR  #(650) that replaces this one.  So closing this PR.

**Pull request closed without merging**
