### PR TITLE
Initialize mocha-generators so tests run

### PR DESCRIPTION
**Pull request by chrisgeo**
Hey Nightmare Team - it looks like mocha test suite isn't automatically initializing `mocha-generators` so the tests only appear to run and succeed, instead of running.

**Branch**: Master
**Commit**: 748a2b2b14163d34e89108250e34553d991e7913

### Use-Case
Modify any test to have a `console.log` - never logs to console.

### Solution
Setup needs `require('mocha-generators').install()`

### CODE REVIEW

**Comment by LarryBattle** [comment]
:+1: It says it right there in the readme. https://github.com/vdemedes/mocha-generators

**Comment by tgohn** [comment]
:+1:  need to recover test

**Comment by rhysd** [comment]
This should be merged ASAP because I think currently all tests are passed wrongly.
In my environment, below tests failed after adding `require('mocha-generators').install()` as below.

```
31 passing (43s)
2 failing

1) Nightmare rendering should take a clipped screenshot:
   Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


2) Nightmare rendering "after each" hook for "should take a clipped screenshot":
   Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by matthewmueller** [comment]
yikes, just noticed this. thanks!

**Comment by rhysd** [comment]
:+1:

**Pull request merged**
