### PR TITLE
Run it.only, and add option to provide env vars to electron process

### PR DESCRIPTION
**Pull request by rfink**
Addresses issue #704, also removes "it.only" from unit tests (assuming that was unintentional).

I admit that I'm not sure what to write for a unit test here.  If you can give me some guidance, that would great.  Otherwise, existing tests pass, and a test run on my machine appears to use the TZ environment variable.  Thanks!

### CODE REVIEW

**Comment by rosshinkley** [comment]
> also removes "it.only" from unit tests (assuming that was unintentional).

Yes, it was unintentional.  Streams got crossed.  (This was also fixed in #697, fwiw.)

> I admit that I'm not sure what to write for a unit test here. If you can give me some guidance, that would great.

I think the easiest thing to do would be to use a custom `.action()` action to pull the environment variable from Electron's `process`.  You should then be able to create an instance with an environment variable, use the custom action to get that variable, and test accordingly.

**Comment by rfink** [comment]
Thanks!  I'll get that going.

**Comment by rfink** [comment]
So what I'm finding, is that the "env" object doesn't get attached to the ChildProcess object in a way that node can access it (i.e. this.child.env, this.proc.env, or this.proc._handle.env).  Unless I'm missing something, it might be hidden under the covers in V8.  Do you have any other suggestions?

**Comment by rosshinkley** [comment]
You should be able to pull `env` off of `process` like you might for any ordinary process, I think.  Off the cuff:

```js
var Nightmare = require('nightmare');

Nightmare.action('envtest',
  function(name, options, parent, win, renderer, done) {
    parent.respondTo('envtest', function(done){
      done(null, process.env);
    });
    done();
  },
  function(done) {
    this.child.call('envtest', done);
  });

var nightmare = Nightmare();

nightmare.goto('http://example.com')
  .envtest()
  .then((r)=> {
    console.log(r);
  });
```
... should be enough to at least make sure you can get the environment variables back.

**Comment by rfink** [comment]
That's great, thanks!  That makes a lot of sense, I had to learn a little how the process communication was working.  I really appreciate your help and patience.

**Comment by rosshinkley** [comment]
No problem! :)

One minor nit: could you remove the `console.log`?

**Comment by rfink** [comment]
Whoops - my mistake.  Removed.  Thanks!

**Pull request merged**
