### PR TITLE
page event listener fix

### PR DESCRIPTION
**Pull request by antpaw**
untested

### CODE REVIEW

**Comment by matthewmueller** [comment]
what does this fix?

**Comment by antpaw** [comment]
it logs to the bash the page events like alert and error with `DEBUG=nightmare:log`

**Comment by rosshinkley** [comment]
The change to `page` from `page-error`, `page-log` etc was an intentional one.  Take a look at the default preload script, specifically at how [page errors are handled](https://github.com/segmentio/nightmare/blob/master/lib/preload.js#L6-L8) and consequently [transmitted to Nightmare](https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L90-L92).  All of the messages are (to the best of my knowledge) still being logged to `debug`, but are logically grouped together using the same event.

**Comment by antpaw** [comment]
it was intentional and i understand this change how ever only the child process does this correct (as you mentioned). https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L90-L92 

the parent process doesn't listen to `page` it listens to `page-error` and thats what die pr is fixing. https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L111-L117

**Comment by rosshinkley** [comment]
@antpaw Ah, I see.  I must have misread the original diff.  It looked like in passing it was adding the `page-*` events back.  At any rate, I think you are correct. The parent process should listen to `page`.  +1. :)

One nit: I think the page handler should handle variable arguments.  Something like:

```js
this.child.on('page', function(){                                                               
  log.apply(null, ['page'].concat(sliced(arguments)))                                           
}); 
```
... or if the `page-*` convention should be kept for `debug`, something like:

```js
this.child.on('page', function(){                                                               
  log.apply(null, ['page-'+arguments[0]].concat(sliced(arguments,1)))                           
});
```

Re testing, the tests for ensuring `page` is handled are already there ([alert](https://github.com/segmentio/nightmare/blob/master/test/index.js#L688-L694), [prompt](https://github.com/segmentio/nightmare/blob/master/test/index.js#L704-L721), and [confirm](https://github.com/segmentio/nightmare/blob/master/test/index.js#L704-L721) are good examples), but simply test that the events are emitted from the child and not submitted to debug.  Testing debug output would probably require using a mock (like mockery).

**Comment by matthewmueller** [comment]
> I think the page handler should handle variable arguments

+1

then i think we're good to go :-)

**Comment by matthewmueller** [comment]
thanks!

**Pull request merged**
