### PR TITLE
Adding http status code

### PR DESCRIPTION
**Pull request by rfink**
Addresses #157

### CODE REVIEW

**Comment by johntitus** [comment]
I like the idea, but this implementation is setting the status whenever the `onResourceReceived` callback fires.  That callback is "[invoked when a resource requested by the page is received](http://phantomjs.org/api/webpage/handler/on-resource-received.html)".  Every external javascript, stylesheet, etc causes this to fire.  So the status code you receive may be for something other than the URL itself.

**Comment by rfink** [comment]
Right, that makes sense.  I included a check in there to make sure that the url of the response matched the url of the page requested by 'goto'

**Comment by johntitus** [comment]
I see, sorry I missed that. Next question - what happens if the user sets a `resourceReceived` callback? May need to catch that an wrap it in the `exports.on` method.

**Comment by rfink** [comment]
No worries, I'm happy you are keeping a close eye on it.  As far as the next issue, I'll take a look and see if I can make a recommendation.  Great point.

**Comment by johntitus** [comment]
One more potential issue - If you `.goto('http://www.reddit.com')`, it gets translated into `http://www.reddit.com/` with the trailing slash. I think this would cause this method to 'miss' the response.

**Comment by johntitus** [comment]
Possible way to do it, at the end of this conversation:

https://github.com/ariya/phantomjs/issues/10185

**Comment by reinpk** [comment]
in `nightmare@2.x` you can listen for the `did-get-response-details` event, and inspect the arguments for the status code — there's enough information in there to pinpoint the html/url requested

**Pull request closed without merging**
