### PR TITLE
Adjusted example script and readme file

### PR DESCRIPTION
**Pull request by oliviervaillancourt**
2 changes:
1) Made the example script shown in the readme.md to actually be the
content of example.js (fix the existing mismtach)
2) small correction to be able to run the example directly after install
(at least on windows) by including the 'node_module\nightmare' as part
of the path and changing yahoo.js to example.js

### CODE REVIEW

**Comment by oliviervaillancourt** [comment]
@Mr0grog @rosshinkley,

Thanks for encouraging me to contribute.  I hope I got it right this time.  I closed #643 and created this one based on the latest.

Let me know if I did it wrong or if you have questions.
Olivier

**Comment by rosshinkley** [comment]
@oliviervaillancourt Pat one looks great, thanks for fixing that.  Part two I'd _probably_ leave as simply `example.js`.  The example is in the root of the project directory and is (I think) fairly obvious which example we're referring to.  The only remaining thing I can think of is possibly changing the README to say `example.js` instead of `yahoo.js` under the Examples heading on line 55 (which isn't your fault, I think it's been that way for quite a while).

@Mr0grog Thoughts?

**Comment by Mr0grog** [comment]
Oh, ha, paths, didn’t even think about how those would be different on Windows when I noted it in #643 :(
Probably agree with @rosshinkley there.

**Comment by oliviervaillancourt** [comment]
Sounds good to me.  I can make the change later on today and update the PR
(I guess this is doable, I've never tried to update a PR before)

Thanks

**Comment by Mr0grog** [comment]
@oliviervaillancourt just make another commit on the same branch and it’ll automatically get picked up :)

**Comment by oliviervaillancourt** [comment]
Thanks Rob,

I'll try that tonight.

**Comment by oliviervaillancourt** [comment]
Hey @rosshinkley and @Mr0grog,

I think I've updated this PR with the outcome of the discussion by simply stating `example.js` on line 55.

Let me know if you feel this should be done otherwise.

Thanks for your help

**Comment by Mr0grog** [comment]
Looks awesome to me. Thanks!

**Comment by rosshinkley** [comment]
Looks great.  Marking for inclusion.  Thanks for the effort, @oliviervaillancourt!

**Pull request merged**
