### PR TITLE
readme: update mocha example

### PR DESCRIPTION
**Pull request by dunn**
As-is the test will time out.

### CODE REVIEW

**Comment by dunn** [comment]
Actually the test still doesn't work; it "passes" no matter what.  Any idea what the problem there is?

**Comment by noahtkeller** [comment]
Since it's a generator you need to yield at the beginning of the chain. Also, you will no longer need the done() callback, or done variable in the generator declaration.

    yield nightmare
      .goto('http://yahoo.com')

I removed the .end() in the chain as well.

Also, the selector won't return the right results, since the first results are from yahoo image search. The following selector delivers the desired results:

    #main .searchCenterMiddle > li:nth-child(2) a

**Comment by noahtkeller** [comment]
var Nightmare = require('nightmare');
    var expect = require('chai').expect; // jshint ignore:line

    require('mocha-generators').install();

    describe('test yahoo search results', function () {
      it('should find the nightmare github link first', function*() {
        var nightmare = Nightmare();
        yield nightmare
          .goto('http://yahoo.com')
          .type('form[action*="/search"] [name=p]', 'github nightmare')
          .click('form[action*="/search"] [type=submit]')
          .wait('#main')
          .evaluate(function () {
            return document.querySelector('#main .searchCenterMiddle > li:nth-child(2) a').href
          })
          .then(function (link) {
            expect(link).to.equal('https://github.com/segmentio/nightmare');
          })
      });
    });

**Comment by dunn** [comment]
Awesome; PR updated. Thanks!

**Comment by Mr0grog** [comment]
FYI—all the examples in the readme used to use generators and were explicitly changed to *not* use them several months ago. Which is to say, it might be better to make this PR just use promises. (Though it sounds like it still would've needed fixing anyway!)

**Comment by rosshinkley** [comment]
I agree with @Mr0grog.  The examples should probably use plain promises to minimize external dependencies.

**Comment by dunn** [comment]
Gotcha.  I might have time to update this later in the week, but if anyone wants to take care if it first, plesase do.

**Comment by dunn** [comment]
I ended up not using Nightmare for the project that prompted this, so I'm not going to have time to rewrite and test the example code.

**Pull request closed without merging**
