### PR TITLE
.wait() accepts multiple selectors as OR

### PR DESCRIPTION
**Pull request by mattxgreen**
Retains original functionality of .wait(), but now allows multiple selectors to be specified as an OR condition:

`.wait('div#this-one','div#that-one')`

This will wait for either selector. Optional soft timeout is still intact.

### CODE REVIEW

**Comment by matthewmueller** [comment]
Hey @mattxgreen, thanks for taking the time to work on this!

I'm a bit torn on this because I personally think we've already overloaded `wait()` way too much. On the other hand I totally understand this use case.

I think it may make more sense to make this into a custom action and keep it out of core though. There's another use case I've found myself wanting around this which is wait until the first of N selectors becomes available. This is sort of the `Promise.all`, while there's another case for a `Promise.race`. But by changing the API in this way, we only cover one of these use cases. 

What do you think?

**Comment by mattxgreen** [comment]
You'll have to elaborate on "the first of N selectors". I understand what you've stated to mean, when any one of a number of selectors is found. If that is the case, that is exactly what this PR does.

**Comment by matthewmueller** [comment]
@mattxgreen oh my mistake, I had it reversed. I guess the opposite use case also seems valid to me: an `ALL` selectors condition. 

Given that both seem like equally valid use cases for a `.wait(sel1, sel2, sel3...)`, it could lead to some confusion. I wonder if we could implement `waitOne(...)` or `waitAll(...)`, though I still think it's probably best to just defer to custom actions.

**Comment by mattxgreen** [comment]
I see both cases having merit, but for me this is the most useful case. I have been having troubles when navigating to a page where it can be one of two pages. .wait() with a fixed delay is unreliable, so being able to look for 'this' or 'that' is a reliable alternative. The most common use I see, is login success/fail, and waiting for either page. I'm also using it for a gradual rollout on ci/cd, and detecting the old version vs new version. I also see these cases being more common than a .wait() with multiple selectors for ALL, but I am obviously biased.

This PR is about 20 lines, very 'cheap', and doesn't modify any existing functionality. Would love to see it in the codebase, but if I'm the only one, I'll see if I can make it into an external module.

**Comment by matthewmueller** [comment]
Let's keep it as a separate action for now – here's an example of how you'd set something like that up:

```js
const Nightmare = require('nightmare')

main().catch(console.error)

async function main() {
  Input(Nightmare)

  const nightmare = Nightmare({ show: true })

  await nightmare.goto('https://google.com')
  await nightmare.input('#lst-ib', 'nightmare is')
  await sleep(5000)
  await nightmare.input('#lst-ib', ' awesome')
  await nightmare.end()
}

function sleep(ms) {
  return new Promise(res => setTimeout(res, ms))
}

function Input(Nightmare) {
  Nightmare.action(
    'input',
    function(name, options, parent, win, renderer, done) {
      parent.respondTo('input', function(value, done) {
        var chars = String(value).split('')

        function type() {
          var ch = chars.shift()
          if (ch === undefined) {
            return done()
          }

          // keydown
          win.webContents.sendInputEvent({
            type: 'keyDown',
            keyCode: ch
          })

          // keypress
          win.webContents.sendInputEvent({
            type: 'char',
            keyCode: ch
          })

          // keyup
          win.webContents.sendInputEvent({
            type: 'keyUp',
            keyCode: ch
          })

          // defer function into next event loop
          setTimeout(type, options.typeInterval)
        }

        // start
        type()
      })
      done()
    },
    function(selector, text, done) {
      // focus, type
      return this.evaluate_now(
        selector => document.querySelector(selector).focus(),
        () => this.child.call('input', text, done),
        selector
      )
    }
  )
}
```

Thanks for your efforts!

**Pull request closed without merging**
